### PR TITLE
Add support to additional platforms

### PR DESCRIPTION
**Pull request by JeisonSanches**
Well... there is  a lot of changes:
- transform into a plugin
- handles the compilation of the dynamic library on each platform
- refactor the bindings following the standards used in ffi projects
- add a c callback from dart
- update the pure-dart example (inside `bin`)

And as a consequence of all the above, it makes the code portable for other additional platforms (macOS and iOS) and also improves the use on the other already supported ones (without the need for a binary explicitly included in the project).

## 
As specified in the `README` file, I tested it on the following devices/platforms:

- Windows 11 Pro 22H2 (22621.1105) 
   CPU: AMD Ryzen 3600
   Ram: 16gb

- Android 13
  CPU: Snapdragon 730
  Ram: 4gb

- Pixel 3a API 33 Android x64 emulator

At the moment, I am not able to test it on macOS, iOS, and Linux, but it _should_ work (it may need some minor tweaking).

##
Well, that's basically it. Thanks for coming up with the idea of migrating the code to dart and doing the initial setup!

 I hope to be able to continue to contribute :)

### CODE REVIEW

**Comment by azkadev** [comment]
Thank you very much for wanting to contribute a lot, but sorry I can't accept this because you made my library only run on the client side (Flutter App)

**Comment by azkadev** [comment]
@JeisonSanches 

Can you help me?
I tried your project it worked but only for android, I tried to build for the windows platform, and linux didn't work

**Comment by azkadev** [comment]
> > Thank you very much for wanting to contribute a lot, but sorry I can't accept this because you made my library only run on the client side (Flutter App)
> 
> Currently, [we don't have a way](https://github.com/dart-lang/sdk/issues/50565) to have a package like this one to work _seamleslly_ for both Dart and Flutter. But I liked the idea (as you did) to split in two different packages: `whisper_dart` and `whisper_flutter`. That is exactly what I was going to suggest.
> 
> > @JeisonSanches
> > Can you help me? I tried your project it worked but only for android, I tried to build for the windows platform, and linux didn't work
> 
> I can try. Could you share the build errors you got as well as the details of your environment?

I tried to compile on linux it shows an error like this
command: `flutter build linux --release -v`
```bash
---
[        ] FAILED: plugins/whisper_flutter/shared/libwhisper.so 
[        ] : && /usr/bin/clang++ -fPIC -std=c++2a -O3 -DNDEBUG   -shared -Wl,-soname,libwhisper.so -o plugins/whisper_flutter/shared/libwhisper.so plugins/whisper_flutter/shared/CMakeFiles/whisper_flutter.dir/main.cpp.o
plugins/whisper_flutter/shared/libwhisper.a  plugins/whisper_flutter/shared/libggml.a && :
[        ] /usr/bin/ld: plugins/whisper_flutter/shared/libwhisper.a(whisper.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
[        ] /usr/bin/ld: plugins/whisper_flutter/shared/libggml.a(ggml.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)

---- 
[        ] ninja: build stopped: subcommand failed.
[  +10 ms] Building Linux application... (completed in 31.2s)
[        ] "flutter linux" took 34,237ms.
[   +3 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:183:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
```

**Comment by JeisonSanches** [comment]
@azkadev Could you try it again adding `-fPIC` to `CMAKE_CXX_FLAGS ` in the `sr/CMakeLists.txt` file?

**Comment by JeisonSanches** [comment]
@azkadev Did you get success with it?

**Comment by azkadev** [comment]
> @azkadev Could you try it again adding `-fPIC` to `CMAKE_CXX_FLAGS ` in the `sr/CMakeLists.txt` file? Also, before you try to build again run:
> 
> ```
> sudo make uninstall
> sudo make clean
> ```
Still can't, the same error appears, maybe if you don't mind + have time please make another pull request, sorry I bothered you because I don't really understand cpp + compile cmake

Sorry, my English is bad

**Comment by JeisonSanches** [comment]
> Still can't, the same error appears, maybe if you don't mind + have time please make another pull request, sorry I bothered you because I don't really understand cpp + compile cmake
> 
> Sorry, my English is bad

Don't worry, mate. I fixed the error in my latest commits: now I'm able to build the project with no erros using a Ubuntu VM. Give it a try.

**Comment by azkadev** [comment]
Thank you very much for helping me, now thanks to you my library can run on various platforms

**Comment by Tryad0** [comment]
With 'whisper_flutter 0.0.4' I get some errors on IOS device as well as on Android device.

IOS

Lexical or Preprocessor Issue (Xcode): '../../src/whisper_flutter.c' file not found
/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/ios/Classes/whisper_dart.c:2:9


Android

Execution failed for task ':whisper_flutter:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/src/CMakeLists.txt: Build command failed.
  Error while executing process /Users/xxx/Library/Android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/src -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=19 -DANDROID_PLATFORM=android-19 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393 -DCMAKE_ANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393 -DCMAKE_TOOLCHAIN_FILE=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/xxx/Library/Android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/xxx/Desktop/Projekte/Zaya/zaya/build/whisper_flutter/intermediates/cxx/Debug/214s131y/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/xxx/Desktop/Projekte/Zaya/zaya/build/whisper_flutter/intermediates/cxx/Debug/214s131y/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a -GNinja}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done

  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/Library/Android/sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:6 (project)

  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Error at CMakeLists.txt:13 (add_library):
    Cannot find source file:

      whisper.cpp/ggml.c

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
    .hpp .hxx .in .txx

  CMake Error at CMakeLists.txt:12 (add_library):
    Cannot find source file:

      whisper.cpp/whisper.cpp

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
    .hpp .hxx .in .txx

  CMake Error at CMakeLists.txt:13 (add_library):
    No SOURCES given to target: ggml

  CMake Error at CMakeLists.txt:12 (add_library):
    No SOURCES given to target: whisper

  CMake Generate step failed.  Build files cannot be regenerated correctly.



Thanks a lot for your work!

**Comment by Tryad0** [comment]
I got an error using 'whisper_flutter 0.0.4' on IOS and also Android:

IOS

Lexical or Preprocessor Issue (Xcode): '../../src/whisper_flutter.c' file not found
/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/ios/Classes/whisper_dart.c:2:9


Android

Execution failed for task ':whisper_flutter:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/src/CMakeLists.txt: Build command failed.
 Error while executing process /Users/xxx/Library/Android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/src -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=19 -DANDROID_PLATFORM=android-19 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393 -DCMAKE_ANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393 -DCMAKE_TOOLCHAIN_FILE=/Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/xxx/Library/Android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/xxx/Desktop/Projekte/Zaya/zaya/build/whisper_flutter/intermediates/cxx/Debug/214s131y/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/xxx/Desktop/Projekte/Zaya/zaya/build/whisper_flutter/intermediates/cxx/Debug/214s131y/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -B/Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a -GNinja}
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done

  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/Library/Android/sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:6 (project)


  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)


  CMake Warning at /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    /Users/xxx/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
    /Users/xxx/.pub-cache/hosted/pub.dev/whisper_flutter-0.0.4/android/.cxx/Debug/214s131y/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)


  CMake Error at CMakeLists.txt:13 (add_library):
    Cannot find source file:

    whisper.cpp/ggml.c

   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
   .hpp .hxx .in .txx


  CMake Error at CMakeLists.txt:12 (add_library):
    Cannot find source file:

   whisper.cpp/whisper.cpp

   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
   .hpp .hxx .in .txx


  CMake Error at CMakeLists.txt:13 (add_library):
    No SOURCES given to target: ggml


  CMake Error at CMakeLists.txt:12 (add_library):
    No SOURCES given to target: whisper


  CMake Generate step failed.  Build files cannot be regenerated correctly.



Thanks a lot for your work!

**Pull request merged**
